from tkinter import CENTER


class Styles:
    PRIMARY_COLOR = "#C98686"
    SECONDARY_COLOR = "#dfc3c3"
    WHITE_COLOR = "#FFFFFF"
    BLACK_COLOR = "#000000"

    FONT_ROBOTO = "Roboto"
    FONT_ROBOTO_12 = f"{FONT_ROBOTO} 12"
    FONT_ROBOTO_13 = f"{FONT_ROBOTO} 13"
    FONT_ROBOTO_15 = f"{FONT_ROBOTO} 15"

    ANCHOR_CENTER = CENTER
